
services:
  postgres:
    image: postgres:15.7
    restart: unless-stopped
    container_name: postgresql-15.7
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postdb"
        POSTGRES_DB: "chat_app"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    volumes:
        - ./rabbitmq-data:/var/lib/rabbitmq
        - ./rabbitmq-logs:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
  rabbitmq-data:
  rabbitmq-logs:

